-- SUPABASE_PATCH_044.sql
-- Adds submission_tokens and pending_submissions tables for the shareable
-- submission link flow (gov10). Tokens are generated by admins and shared
-- with external contributors; recipients fill out a public form without login.
--
-- IMPORTANT: Run this manually in the Supabase SQL Editor. Do NOT run via CLI.
-- ============================================================================

-- ── submission_tokens ───────────────────────────────────────────────────────
-- One row per shareable link. Admins create tokens scoped to an org + module.
CREATE TABLE IF NOT EXISTS submission_tokens (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  token       text        UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(24), 'hex'),
  org_id      uuid        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  module      text        NOT NULL CHECK (module IN ('app_inventory', 'ai_tool_catalog')),
  label       text,
  created_by  text,
  expires_at  timestamptz NOT NULL,
  revoked     boolean     NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── pending_submissions ──────────────────────────────────────────────────────
-- One row per external form submission. Admins review and approve/reject.
CREATE TABLE IF NOT EXISTS pending_submissions (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  token_id        uuid        NOT NULL REFERENCES submission_tokens(id) ON DELETE CASCADE,
  org_id          uuid        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  module          text        NOT NULL CHECK (module IN ('app_inventory', 'ai_tool_catalog')),
  submitter_name  text,
  submitter_email text,
  payload         jsonb       NOT NULL DEFAULT '{}',
  status          text        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by     text,
  reviewed_at     timestamptz,
  review_notes    text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- ── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE submission_tokens    ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_submissions  ENABLE ROW LEVEL SECURITY;

-- Anon: read tokens (needed for public link validation)
CREATE POLICY "anon_select_submission_tokens"
  ON submission_tokens FOR SELECT
  TO anon
  USING (true);

-- Anon: insert pending submissions (public form submit)
CREATE POLICY "anon_insert_pending_submissions"
  ON pending_submissions FOR INSERT
  TO anon
  WITH CHECK (true);

-- Authenticated: full access to both tables
CREATE POLICY "auth_all_submission_tokens"
  ON submission_tokens FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "auth_all_pending_submissions"
  ON pending_submissions FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
