-- SYNC_BACKLOG_PART_10.sql -- items 361-396 of 396
-- Run all 10 parts. Safe to re-run.

INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('ma4', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 3, 'M&A portfolio view â€” cross-org list of all M&A assessments visible to the current user (Group/Platform tier). Shows target name, deal type, risk rating, score, and linked entity status. Accessible from the Group/Platform dashboard.', false, 'Medium', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('ma5', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 4, 'Audit log for M&A â€” wire auditLog() into maSave() (create + complete), maDeleteAssessment(), and maConfirmAddEntity() to maintain full platform audit trail. Same pattern as CIS and AI Unified audit calls.', false, 'Low', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('ps1', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 5, 'Pricing Schedule â†’ M&A cost resolution: expand MA_TOOL_TYPE_MAP in ma_cdd.js to cover the full 25 tool types (MDR device, MDR identity, MDR/SOC, SAT, NGFW, email variants, vuln external/internal, pen tests, vCISO, etc.) so psGetForType() resolves pricing for all M&A question buckets, not just the current 6.', false, 'Medium', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('ps2', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 6, 'Pricing Schedule cross-module use â€” surface psGetForType() resolved pricing in CIS POAM cost estimates and TPRA remediation cost fields. When a finding maps to a known tool type, show the MSP/org rate alongside the platform default so the assessor sees their actual pricing.', true, 'Low', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('rc1', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 7, 'Insurance Readiness: Cost to Remediate tab â€” map insurance survey gaps (questions answered ''no'' that affect score) to tool types and surface pricing schedule estimates, same pattern as CIS and Tech Stack cost tabs.', true, 'Medium', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('rc2', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 8, 'Remediation cost: 5-year schedule view â€” extend the Cost to Remediate tab with a 5-year cost projection (Year 1: setup + annual; Years 2â€“5: recurring only), same format as M&A CDD schedule. One-time setup fees appear only in the period the tool is deployed.', false, 'Low', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('rc3', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 9, 'Remediation cost: show ''also covers'' on matched rows â€” when psGetForType() returns a bundle SKU (covers[] array), note which additional gap types it satisfies on the cost row (e.g. ''Also satisfies: Email Backup, Email DLP'') so the assessor sees the full value of one purchase.', false, 'Low', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gr1', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 10, 'Gap Register â€” consolidated cross-module gap list under Reports nav. Merges CIS Controls, Insurance Readiness, and Tech Stack gaps by tool type into one unified view with pricing from the Pricing Schedule.', true, 'High', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gr2', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 11, 'Tool Gap Register â€” three fixes: (1) rename from ''Gap Register'' to ''Tool Gap Register'' throughout, (2) child org pricing: two-level inheritance (child â†’ father â†’ grandfather) so child orgs see MSP pricing in the gap register, (3) tier banner visibility count shows org''s own tier scope rather than logged-in user''s full visibility', true, 'High', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gr3', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 12, 'Tool Gap Register â€” clickable source links: CIS/Insurance/Tech Stack badges navigate to source assessment; CIS rows show specific safeguard IDs inline (e.g. 1.1 Â· 3.4 Â· 6.8) for back-checking; Insurance/TS show gap count', true, 'Medium', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gr4', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 13, 'Tool Gap Register â€” Tech Stack as source of truth for tool existence: if TS records any ''yes'' for a tool type, CIS and Insurance flags for that type are suppressed (they reflect config gaps, not absence). Prevents EDR appearing as missing when Sentinel One is deployed.', true, 'High', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gr5', 'ma_cdd', 'M&A Cyber Due Diligence', 1, 14, 'Tool Gap Register â€” CIS â†’ tool mapping corrected to safeguard level: only safeguards that literally require deploying a specific tool are mapped; process/config/policy safeguards excluded. RC_CIS_CTRL_MAP (control-level) replaced by RC_CIS_SF_MAP (safeguard-level). Key removals: 7.1/7.2/7.7 (VM process), 10.2-10.5 (OS configs), 8.1-8.8/8.10-8.12 (log config), 12.1-12.6/12.8 (network architecture), 17.1-17.6/17.8-17.9 (IR process), controls 5+15 removed entirely. New: 7.3/7.4â†’mdm, 13.2/13.7â†’edr, 2.5-2.7â†’edr, 16.13+18.5 added.', true, 'High', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig1', 'ai_governance', 'AI Governance', 1, 0, 'AI Risk Register â€” AI-prefixed risk IDs (AI-001, AI-002â€¦), columns: Category, AI System (dropdown from catalog), Data Classification, Human-in-Loop, Likelihood, Impact, Rating, Status. Expandable rows show NIST AI RMF and ISO 42001 control chips. Filter tabs for Rating and Status. Auto-calculates risk rating from likelihood Ã— impact matrix. Source field distinguishes manual vs ai_assessment entries.', true, 'High', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig2', 'ai_governance', 'AI Governance', 1, 1, 'AI Application Inventory â€” browse and manage the seeded AI tool reference catalog. Table view grouped by vendor, parent-child hierarchy (components shown indented). Compliance columns: DLP, SSO, Logs, DPA, SOC 2 (âœ“/â€” chips). EU AI Act classification, NIST AI RMF controls, ISO 42001 clauses. Approval status badge (Approved / Enterprise Only / Conditional / Not Approved / Under Review). Platform admin mode: edit seeded tool data, add/delete non-seeded tools. Seeded tools cannot be deleted.', true, 'High', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig3', 'ai_governance', 'AI Governance', 1, 2, 'Per-org AI tool inventory â€” org users mark which catalog tools they use, set org-specific approval status override, add custom tools not in catalog. Stored in ai_org_tools table (PATCH_037). Feeds a dashboard widget showing approved/conditional/not-approved tool breakdown.', true, 'Medium', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig4', 'ai_governance', 'AI Governance', 1, 3, 'AI Risk Register auto-population from AI Assessment POAM â€” same pattern as CIS POAM feeding main risk register. Source = ''ai_assessment''. Sync button on AI Risk Register or auto-runs on AI Assessment completion.', false, 'Medium', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig5', 'ai_governance', 'AI Governance', 1, 4, 'AI Tool Catalog admin interface â€” allow platform admins to manage component relationships (ai_tool_components) via the admin modal UI. Currently components are seeded-only; admin UI would allow adding/removing parentâ†’child links.', false, 'Low', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig6', 'ai_governance', 'AI Governance', 1, 5, 'Dashboard AI tool breakdown widget â€” show approved / conditional / shadow IT tool counts on the home dashboard for orgs that have AI Governance module access. Small stat card or strip similar to the portfolio risk bar.', true, 'Low', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig7', 'ai_governance', 'AI Governance', 1, 6, 'AI Governance Tabletop ACL â€” in Module Management, map ''AI Governance Tabletop'' (tt_ai) page to the AI Governance module column so AI Governance-only users can access it via the Exercises hub. Admin action: Settings â†’ Module Management â†’ AI Governance Tabletop row â†’ check AI Governance column â†’ Save.', false, 'Low', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('aig8', 'ai_governance', 'AI Governance', 1, 7, 'AI tool catalog â€” seeded tools: Copilot Free, Microsoft 365 Copilot, Azure AI Foundry + APIM (component), Ctrl AI (Expedient). PATCH_038 adds these. When adding a parent tool from catalog, all component children are auto-added at the same status.', true, 'Medium', NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov1', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 0, 'Application Inventory scaffold â€” list view of all business applications. Fields: app name, description, business owner, hosting type (SaaS/Cloud/On-Prem/Hybrid), status (Active/Decommissioned/Under Review), vendor/supplier, authentication method (MFA enforced, SSO), data classification (PII, payment, health, IP, confidential), date added, last reviewed.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov2', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 1, 'Application risk and criticality â€” criticality rating per app (Critical/High/Medium/Low) with rationale. Risk level derived from criticality + data classification. Regulatory scope flag. Displayed as sortable/filterable badges on list view.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov3', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 2, 'Application BCDR classification â€” per-app BCDR fields: recovery priority (Tier 1/2/3), RTO, RPO, backup method, dependencies (other apps or vendors), BCDR owner contact. Summary view of Tier 1 apps for exec reporting.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov4', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 3, 'Application IR classification â€” per-app IR fields: in-scope for IR (yes/no), IR priority tier, key technical contact, vendor IR contact, escalation path, last incident date. IR priority auto-suggested from criticality + data classification. Used to pre-populate IR runbooks in tabletop exercises.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov5', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 4, 'Vendor Directory scaffold â€” list view of all vendors. Fields: vendor name, product/service, website, category (Cloud Infrastructure/SaaS/Managed Services/Professional Services/Hardware/Telecom/Other), primary contact name and email, status (Active/Inactive/Under Review), date added, last reviewed.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov6', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 5, 'Vendor criticality and risk tier â€” per-vendor: business criticality (Critical/High/Moderate/Low) with rationale, risk tier (mirrors TPRA), data access types (PII, payment, health, IP, infrastructure), jurisdiction, data residency. Certifications held (SOC 2 Type I/II, ISO 27001, ISO 42001, PCI DSS, HIPAA BAA, CSA STAR). Last TPRA assessment date with link to TPRA record if one exists.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov7', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 6, 'Vendor contract and compliance tracking â€” per-vendor: contract renewal date (90/30 day banner warnings), SLA terms summary, liability and insurance coverage notes, NDA in place, DPA in place, right to audit clause. Dashboard widget showing vendors with renewals in next 90 days.', false, NULL, NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov8', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 7, 'Vendor BCDR and IR contacts â€” per-vendor BCDR: in BCDR plan (yes/no), BCDR dependency tier, alternative vendor or workaround documented. Per-vendor IR: 24/7 IR contact name and phone, incident notification SLA (hours), breach notification clause in contract, last confirmed IR contact date. Used to pre-populate vendor notification checklist in tabletop exercises.', false, NULL, NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov9', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 8, 'Department field on Application Inventory and AI Tool Catalog â€” free-text department entry per app/tool that auto-populates a per-org department list. When adding or editing, the department field is a text input with autocomplete suggestions drawn from previously entered departments for that org. Departments are stored in a new org_departments table (or derived from existing entries). Displayed as a badge on each row.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov10', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 9, 'Shareable submission links with timeout for Application Inventory and AI Tool Catalog â€” platform admin or admin can generate a time-limited link (configurable: 24h / 7d / 30d) for a specific org. Anyone with the link can submit a new app or AI tool on behalf of their department without a login. Submissions land in a ''Pending Review'' status. Admin sees a pending queue and can approve (promote to Active) or reject. Link can be revoked early. Stored in a submission_tokens table with org_id, module (app_inventory / ai_tool_catalog), expires_at, and revoked flag.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov11', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 10, 'Regulatory scope tagging for Application Inventory and AI Tool Inventory â€” select which compliance frameworks apply (SOX, PCI-DSS, HIPAA, PIPEDA/Privacy) plus a freetext ''Other'' field. Show framework abbreviation badges in the table row. Governance hub reorganized into logical sub-groups: Inventories / Risk Registers / Other. IR Priority Tier (P1â€“P4) now visible alongside BCDR tier in the table.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov12', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 11, 'AI Tool Inventory â†’ Application Inventory link â€” AI org tools can optionally reference an Application Inventory entry via app_inventory_id FK. When linked, BCDR priority, IR tier, and criticality are inherited from the linked app entry rather than stored separately. In the AI Tool edit modal, a ''Link to Application'' picker lets admin choose from the org''s app_inventory entries. BCDR/criticality treatment for AI Tools follows the linked app; unlinked AI tools keep a lighter risk tier (High/Medium/Low). Also add regulatory_scope to ai_org_tools table.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('gov13', 'governance', 'Governance â€” Application Inventory and Vendor Directory', 2, 12, 'Email submission link â€” when a shareable link is sent to a client/contact via the submission portal (gov10), also send an email with the link. Reduces friction for clients who need to respond to a survey or form. Requires Supabase Edge Function or email provider integration.', false, 'High', NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('ex1', 'exercises_hub', 'Exercises Hub & Scoring', 3, 0, 'Tabletop scoring model â€” 0â€“100 score per completed session. Four dimensions: criticality accuracy (35%), breach declaration quality (30%), IR phase coverage (20%), insurer notification completeness (15%). Weighted average â†’ single score. Stored in tabletop_sessions.exercise_score. Computed at AAR render and written on session complete.', true, NULL, NULL, '[]', 'completed')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('ex2', 'exercises_hub', 'Exercises Hub & Scoring', 3, 1, 'Dashboard exercises chicklet with SVG dial â€” Replaces link-only Exercises widget. SVG dial arc (0â€“100) shows average exercise_score across all completed sessions. Colour-banded: green â‰¥70, amber 40â€“69, red <40, grey = no data. Sessions run count, last exercise date. ''Start New'' CTA.', false, NULL, NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
INSERT INTO backlog_items (id, section_id, section_title, section_phase, sort_order, "text", done, priority, notes, dependencies, status)
VALUES ('ex3', 'exercises_hub', 'Exercises Hub & Scoring', 3, 2, 'Exercises Hub â€” proper landing page replacing current card-grid stub. Stat strip (total sessions, sessions this year, last exercise date). Track cards (Operational, AI Governance, Executive, Vendor/BCDR) each showing last run date and score dial from exercise_score. Recent exercises table. ''Start New Exercise'' CTA per track.', false, NULL, NULL, '[]', 'add')
ON CONFLICT (id) DO UPDATE SET
  section_id=EXCLUDED.section_id, section_title=EXCLUDED.section_title, section_phase=EXCLUDED.section_phase, sort_order=EXCLUDED.sort_order, "text"=EXCLUDED."text", done=EXCLUDED.done, priority=EXCLUDED.priority, status=EXCLUDED.status, updated_at=now();
